version: '3.8'

services:
  neo4j:
    image: neo4j:5.24.1-enterprise
    volumes:  
        - ./logs:/logs
        - ./data:/data
        - ./startup.sh:/startup.sh
        - ./import:/var/lib/neo4j/import
    env_file:
      - .env
    ports:
      - "7474:7474"
      - "7687:7687"
    command: /startup.sh
      
  airflow-web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: webserver
    env_file:
      - .env
    ports:
      - "8080:${AIRFLOW_HTTP_PORT}"
    volumes:
      - ./dags:/opt/airflow/dags
    depends_on:
      - postgres

  airflow-sheduler:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ./airflow-logs:/usr/local/airflow/logs
    env_file:
      - .env
    depends_on:
      - postgres

  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "airflow db init && airflow users create ${AIRFLOW_USER}"
    volumes:
      - ./dags:/opt/airflow/dags
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 

  minio:
    image: minio/minio:latest
    env_file:
      - .env
    ports:
     - "9000:${MINIO_API_PORT}"
     - "9001:${MINIO_CLI_PORT}"
    volumes:
      - minio_storage:/data
    command: server /data --console-address ":9001"

  vertica:
    image: vertica/vertica-ce:24.1.0-0
    env_file:
      - .env
    ports:
      - "5433:5433"
    volumes:
      - vertica_data:/opt/vertica/data
    
volumes:
  postgres_data:
  minio_storage:
  vertica_data: